# Made by migo3 at 02/10/2026 03:02:06 for Steam 1790904859 (beta) build
# forge generated sha256=39e5a04d731a49977137211f6c8afbb5083ef91b55af13a3a8b60e71989ed558

[IClientUser]
interface_id = 1

[IClientUser.BUpdateAppOwnershipTicket]
funcHash = "0xCEDD4F18"
wrapper_rva = "0x74B680"

[IClientUser.GetAppOwnershipTicketExtendedData]
funcHash = "0xC7E71245"
fencepost = "0xC8449840"
argc = 2
wrapper_rva = "0x76A170"

[IClientUser.GetEncryptedAppTicket]
funcHash = "0xE0468CB4"
fencepost = "0xE0B80200"
argc = 1
wrapper_rva = "0x77CD00"

[IClientUser.GetSteamID]
funcHash = "0xD6FC3200"
fencepost = "0xD7058CA5"
argc = 0
wrapper_rva = "0x7A1A60"

[IClientUser.RequestEncryptedAppTicket]
funcHash = "0x25D6BB1D"
fencepost = "0x2646B663"
argc = 2
wrapper_rva = "0x8609C0"

[IClientUtils]
interface_id = 4

[IClientUtils.GetAPICallResult]
funcHash = "0x2D3D3947"
wrapper_rva = "0x764D10"

[IClientUtils.GetAppID]
funcHash = "0x09607EC4"
wrapper_rva = "0x768ED0"
