# Made by migo3 at 29/09/2026 16:22:04 for Steam 1790545198 (beta) build
# forge generated sha256=6cc13c9af2b95aadb4a76f7a30601de48b303dbfa3ce58fc5c8db7a44d495602

[IClientUser]
interface_id = 1

[IClientUser.BUpdateAppOwnershipTicket]
funcHash = "0xCEDD4F18"
wrapper_rva = "0x74AA90"

[IClientUser.GetAppOwnershipTicketExtendedData]
funcHash = "0xC7E71245"
fencepost = "0xC8449840"
argc = 2
wrapper_rva = "0x769580"

[IClientUser.GetEncryptedAppTicket]
funcHash = "0xE0468CB4"
fencepost = "0xE0B80200"
argc = 1
wrapper_rva = "0x77C110"

[IClientUser.GetSteamID]
funcHash = "0xD6FC3200"
fencepost = "0xD7058CA5"
argc = 0
wrapper_rva = "0x7A0E70"

[IClientUser.RequestEncryptedAppTicket]
funcHash = "0x25D6BB1D"
fencepost = "0x2646B663"
argc = 2
wrapper_rva = "0x85FA70"

[IClientUtils]
interface_id = 4

[IClientUtils.GetAPICallResult]
funcHash = "0x2D3D3947"
wrapper_rva = "0x764120"

[IClientUtils.GetAppID]
funcHash = "0x09607EC4"
wrapper_rva = "0x7682E0"
