# Made by migo3 at 06/10/2026 02:01:39 for Steam 1791249696 (beta) build
# forge generated sha256=7b2ae9f805ecba2ae2c733aa934a715f052a16eb481090e1f3cb88d7501c8df8

[IClientUser]
interface_id = 1

[IClientUser.BUpdateAppOwnershipTicket]
funcHash = "0xCEDD4F18"
wrapper_rva = "0x74AFA0"

[IClientUser.GetAppOwnershipTicketExtendedData]
funcHash = "0xC7E71245"
fencepost = "0xC8449840"
argc = 2
wrapper_rva = "0x769A90"

[IClientUser.GetEncryptedAppTicket]
funcHash = "0xE0468CB4"
fencepost = "0xE0B80200"
argc = 1
wrapper_rva = "0x77C620"

[IClientUser.GetSteamID]
funcHash = "0xD6FC3200"
fencepost = "0xD7058CA5"
argc = 0
wrapper_rva = "0x7A1380"

[IClientUser.RequestEncryptedAppTicket]
funcHash = "0x25D6BB1D"
fencepost = "0x2646B663"
argc = 2
wrapper_rva = "0x85FF60"

[IClientUtils]
interface_id = 4

[IClientUtils.GetAPICallResult]
funcHash = "0x2D3D3947"
wrapper_rva = "0x764630"

[IClientUtils.GetAppID]
funcHash = "0x09607EC4"
wrapper_rva = "0x7687F0"
